### ISSUE TITLE
Conversion to CSV fails

### ISSUE THREAD

**Issue by ghost** [Lord-G-INC/bcsv-tool#1]
As of version 2.0.0, conversion from bcsv to csv fails with the following error:

`Error: Error(Utf8 { pos: Some(Position { byte: 0, line: 1, record: 0 }), err: Utf8Error { field: 0, valid_up_to: 3 } })`

I tested this with several bcsv files (including an original, unmodified ActionSound.bcsv from SMG2).

**Comment by Lord-Giganticus** [comment]
Solved (I hope) in [81d8a35](https://github.com/Lord-G-INC/bcsv-tool/commit/81d8a350dbae06dc3098819490e267aa156e67a9)
